### ISSUE TITLE
test fail with NoMethodError looking for "shared_examples_for" method

### ISSUE THREAD

**Issue by pravi** [ianwhite/orm_adapter#23]
``` ruby
Running tests for ruby1.9.1 using debian/ruby-tests.rb...
/media/forge/debian/diaspora/ruby-orm-adapter-0.4.0/spec/orm_adapter/example_app_shared.rb:21:in `<top (required)>': undefined method `shared_examples_for' for main:Object (NoMethodError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from debian/ruby-tests.rb:7:in `block in <main>'
    from debian/ruby-tests.rb:7:in `each'
    from debian/ruby-tests.rb:7:in `<main>'
```

I'm building a debian package for this gem using gem2deb tool.

**Comment by pravi** [comment]
After switching to ruby-tests.rake (see http://ur1.ca/ao6ok) from ruby-tests.rb it worked! Closing.
